                  id                  |         name         | price | stock |                                                                                        description                                                                                        | rating | is_active |                                                                     big_image                                                                      | brand_id 
--------------------------------------+----------------------+-------+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------+----------
 9feeb2bb-3b51-4c15-9abc-4d1caf5860bc | PS5                  | 32000 |    30 |  Experimenta cargas superrápidas gracias a una unidad de estado sólido (SSD) de alta velocidad, una inmersión más profunda con retroalimentación háptica, gatillos adaptables y audio 3D. |      4 | t         | https://www.techinn.com/f/13776/137769821/sony-ps5.jpg                                                                                             |         
 d7fe65a2-7aa4-4cbc-827e-f1a4e750d1f6 | Cámara Nikon         |  9000 |    20 | Captura mejor tus momentos con su cámara de 50mm                                                                                                                                          |      5 | t         | https://cdn-4.nikon-cdn.com/e/Q5NM96RZZo-YRYNeYvAi9beHK4x3L-8kHbA0MlEAVn2W1yKXB-B_2zEtiAgzBX5TShX8lUMVnxSs0ATXqRnkGA==/Views/25492_D3200_front.png |         
 2259c3df-8c19-44ca-ae73-31614d480ba9 | Auriculares Phillips |  8000 |    10 | Escuchar música nunca fué tan placentero.                                                                                                                                                 |      4 | t         | https://www.tiomusa.com.ar/imagenes/archivos/2020-10/26815-auricularvinchaphilipstah4205bk.jpg                                                     |         
 ea868843-211d-478b-a0c7-a8d6d97a371e | Mouse Logitech RGB   |  2400 |     0 | Con sus 3000 DPI aumenta tu presición tanto en diseño gráfico como en videojuegos.                                                                                                        |      4 | f         | https://www.fullh4rd.com.ar/img/productos/Pics_Prod/mouse-logitech-g203-0.jpg                                                                      |         
 8b9c38e5-0a78-4a29-9773-98c264786f94 | Teclado RGB HyperX   |  6800 |     0 | Teclado Mecánico                                                                                                                                                                          |      5 | f         | https://media.kingston.com/hyperx/product/hx-product-keyboard-alloy-origins-core-no-3-zm-lg.jpg                                                    |         
 70b9bcc3-3780-443b-8182-ef56e9546367 | SmartPhone SAMSUNG   | 46000 |   120 | Samsung Galaxy A51 128 GB.Liberado                                                                                                                                                        |      3 | t         | https://http2.mlstatic.com/D_NQ_NP_879201-MLA44443256851_122020-O.webp                                                                             |         
(6 rows)

